export const adjectives = [
    "Happy",
    "Creative",
    "Energetic",
    "Lively",
    "Dynamic",
    "Radiant",
    "Joyful",
    "Vibrant",
    "Cheerful",
    "Sunny",
    "Sparkling",
    "Bright",
    "Shining",
];

export const animals = [
    "Dolphin",
    "Tiger",
    "Elephant",
    "Penguin",
    "Kangaroo",
    "Panther",
    "Lion",
    "Cheetah",
    "Giraffe",
    "Hippopotamus",
    "Monkey",
    "Panda",
    "Crocodile",
];